# Generated by Django 5.2 on 2025-04-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_validation_token_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="L'image de profil de l'utilisateur.", null=True, upload_to='user_profiles/', verbose_name='Image de profil'),
        ),
    ]
