# Generated by Django 5.2 on 2025-04-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomalokuta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
