# Generated by Django 5.2.1 on 2025-05-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomalokuta', '0002_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '👍'), ('dislike', '👎'), ('heart', '❤️'), ('lol', '😂'), ('wow', '😮')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomalokuta.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomalokuta.customuser')),
            ],
        ),
    ]
