# Generated by Django 5.2.1 on 2025-05-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomalokuta', '0004_taskrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
