# Generated by Django 5.2.1 on 2025-05-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomalokuta', '0005_alter_taskrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur ayant déclenché cette tâche.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='bomalokuta.customuser', verbose_name='Utilisateur'),
        ),
    ]
