# Generated by Django 5.2.1 on 2025-05-15 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('niveau_remplissage', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('bac', 'Bac à déchets'), ('centre', 'Centre de recyclage')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('administrateur', 'Administrateur'), ('éco-influenceur', 'Éco-Influenceur'), ('partenaire', 'Partenaire'), ('municipalité', 'Municipalité')], default='utilisateur', max_length=20)),
                ('user_associated', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_terranova', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
        ),
        migrations.CreateModel(
            name='Dechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dechets/')),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('statut', models.CharField(choices=[('signalé', 'Signalé'), ('en_cours', 'En cours de traitement'), ('traité', 'Traité')], default='signalé', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terranova.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terranova.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dechets_signalés', models.IntegerField(default=0)),
                ('dechets_recyclés', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='terranova.customuser')),
            ],
        ),
    ]
